### ISSUE TITLE
Select using multi indexes

### ISSUE THREAD

**Issue by snuids** [opendistro-for-elasticsearch/sql-jdbc#3] opened 2019-03-21 08:05 UTC
Hi,

I am using the driver with jasper report and it works like a charm. However, I cannot make queries such as:

select * from logtstash*

This query is working using the open distro plugin via the Rest API.

Am I missing something ?

Thanks,

**Comment by dai-chen** [comment] 2019-03-21 16:38
Hi, this is related to https://github.com/opendistro-for-elasticsearch/sql/issues/9. We've root caused and will be fixing it.

**Comment by snuids** [comment] 2019-03-21 16:39
Great Thx !

**Comment by vinjosh** [comment] 2019-03-22 09:29
Duplicate of https://github.com/opendistro-for-elasticsearch/sql/issues/9

**Comment by dai-chen** [comment] 2019-03-25 19:23
Fixed and merged.

**Closed as completed by dai-chen** 2019-03-25 19:23 UTC
Labels: duplicate
